In [1]:
import pandas as pd
df = pd.read_csv(r"C:\Users\tanay\Downloads\auto-mpg.csv")
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
395,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
396,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
397,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

In [2]:
df.info
df.describe
df.isnull().sum()

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model year      0
origin          0
car name        0
dtype: int64

In [3]:
df.describe

<bound method NDFrame.describe of       mpg  cylinders  displacement horsepower  weight  acceleration  \
0    18.0          8         307.0        130    3504          12.0
1    15.0          8         350.0        165    3693          11.5
2    18.0          8         318.0        150    3436          11.0
3    16.0          8         304.0        150    3433          12.0
4    17.0          8         302.0        140    3449          10.5
..    ...        ...           ...        ...     ...           ...
393  27.0          4         140.0         86    2790          15.6
394  44.0          4          97.0         52    2130          24.6
395  32.0          4         135.0         84    2295          11.6
396  28.0          4         120.0         79    2625          18.6
397  31.0          4         119.0         82    2720          19.4

     model year  origin                   car name
0            70       1  chevrolet chevelle malibu
1            70       1          buick skylark 320
2            70       1         plymouth satellite
3            70       1              amc rebel sst
4            70       1                ford torino
..          ...     ...                        ...
393          82       1            ford mustang gl
394          82       2                  vw pickup
395          82       1              dodge rampage
396          82       1                ford ranger
397          82       1                 chevy s-10

[398 rows x 9 columns]>

In [4]:
nums = ["cylinders","displacement","horsepower","weight","acceleration","model year","origin","mpg"]
for col in nums:
    df[col] = pd.to_numeric(df[col],errors="coerce")

In [5]:
df.isnull().sum()

mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model year      0
origin          0
car name        0
dtype: int64

In [6]:
df["horsepower"] = df["horsepower"].fillna(
    df["horsepower"].median()
)

In [7]:
df.isnull().sum()

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model year      0
origin          0
car name        0
dtype: int64

In [10]:
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130.0,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.0,2790,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52.0,2130,24.6,82,2,vw pickup
395,32.0,4,135.0,84.0,2295,11.6,82,1,dodge rampage
396,28.0,4,120.0,79.0,2625,18.6,82,1,ford ranger
397,31.0,4,119.0,82.0,2720,19.4,82,1,chevy s-10

In [11]:
df = df.drop("car name",axis=1)

In [12]:
x = df.drop("mpg",axis=1)
x.shape

(398, 7)

In [13]:
y = df["mpg"]
y.shape

(398,)

In [21]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler

lr = LinearRegression()
sc = StandardScaler()

x_train,x_test,y_train,y_test = train_test_split(x,y,random_state = 42, test_size = 0.2)

In [22]:
x_train_std = sc.fit_transform(x_train)
x_test_std = sc.transform(x_test)

In [23]:
lr.fit(x_train_std,y_train)
y_pred = lr.predict(x_test_std)

In [24]:
y_pred

array([32.88140046, 29.55780381, 21.36955005, 16.79734409, 12.4982001 ,
       27.20579297, 27.90034172,  9.77551057, 16.88434148, 22.03432001,
       12.80789558, 36.15459303, 25.17028795, 13.69410403, 23.9851906 ,
        6.38676545, 29.53717565, 23.57394424, 16.32934475, 36.28649078,
       23.71277029, 18.98644465, 28.71675729, 28.74222236, 14.9937939 ,
       34.66185682, 25.48371184, 24.95050273, 21.94949529,  8.78921085,
       28.43042198, 34.85784604, 20.52566418, 26.07137821, 34.25192799,
       11.98882056, 22.93388155, 21.74271783, 12.32731516, 26.75009008,
       26.24028149, 27.42358817, 20.15034925,  7.2688964 , 24.53759706,
       34.94012278, 26.75746176, 24.19444148, 22.51366966, 27.5625466 ,
       22.68143886, 33.67127815, 32.67124307, 10.95619387, 27.70684405,
       10.00691734, 19.76572214, 29.87443683, 23.17483434, 20.47189168,
       16.18259662, 32.09331845, 24.02025492, 20.49935146, 20.92671853,
       25.51057393, 25.11923146, 32.38245245, 28.07654777, 12.71391714,
       31.2720768 , 13.02792301, 10.04768517, 19.42898455, 27.39271123,
       22.12731743, 20.51995099, 29.52906034, 29.33325802, 20.0870444 ])

In [25]:
from sklearn.metrics import mean_absolute_error,root_mean_squared_error,r2_score,mean_squared_error
import numpy as np

print("MAE:", mean_absolute_error(y_test, y_pred))
print("MSE:", mean_squared_error(y_test, y_pred))
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
print("RMSE:", rmse)
print("R2 Score:", r2_score(y_test, y_pred))

MAE: 2.2553632612835637
MSE: 8.197746885824962
RMSE: 2.8631707748272652
R2 Score: 0.8475304239212407

In [42]:
from sklearn.preprocessing import StandardScaler,PolynomialFeatures
from sklearn.pipeline import Pipeline
from sklearn.linear_model import Ridge,Lasso
ridge_model = Pipeline([
    ('poly',PolynomialFeatures(degree=5)),
    ('scaler',StandardScaler()),
    ('ridge',Ridge(alpha=1))
])

In [43]:
ridge_model.fit(x_train,y_train)
ridge_train_pred = ridge_model.predict(x_train)
ridge_test_pred = ridge_model.predict(x_test)

print("\nRidge (degree = 5,alpha=1)")
print("Train Score: ",r2_score(y_train,ridge_train_pred))
print("Test score: ",r2_score(y_test,ridge_test_pred))

Ridge (degree = 5,alpha=1)
Train Score:  0.9131193908900704
Test score:  0.9118089022509638

In [50]:
from sklearn.preprocessing import StandardScaler,PolynomialFeatures
from sklearn.linear_model import Ridge,Lasso
from sklearn.pipeline import Pipeline
lasso_model = Pipeline([
    ('poly',PolynomialFeatures(degree=5)),
    ('scaler',StandardScaler()),
    ('lasso',Lasso(alpha=10,max_iter=10000))
])

In [51]:
lasso_model.fit(x_train,y_train)
lasso_train_pred=lasso_model.predict(x_train)
lasso_test_pred=lasso_model.predict(x_test)

In [52]:
print("\nLasso (degree = 5,alpha=10)")
print("Train Score: ",r2_score(y_train,lasso_train_pred))
print("Test score: ",r2_score(y_test,lasso_test_pred))

Lasso (degree = 5,alpha=10)
Train Score:  0.0
Test score:  -0.00403326341807686